// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/gpfs/home/had/kinoue/E31_ana/AutoDict_vector_CrossSection_.cxx";

#endif
