#include "macro/init.C"

const TString infileroot="~/spectra.root";

void draw_kamano_data(){
  init();
  const double kpThre=1000*(kpMass+pMass);
  TLine line;
  line.SetLineColor(3);
  line.SetLineWidth(3);

  TFile *f=new TFile(infileroot);
  TGraphErrors *data_pimSp=(TGraphErrors*)f->Get("pimSp_CS0");
  TGraph *pimSp_modelA=(TGraph*)f->Get("pimSp_modelA_conv");
  TGraph *pimSp_modelB=(TGraph*)f->Get("pimSp_modelB_conv");
  data_pimSp-> GetYaxis()-> SetTitle("#frac{d^{2}#sigma}{d#Omega dm} #mub/sr MeV");
  data_pimSp-> GetXaxis()-> SetTitle("#pi #Sigma mass [GeV/c^{2}]");
  data_pimSp=GevToMev(data_pimSp);
  pimSp_modelA=GevToMev(pimSp_modelA);
  pimSp_modelB=GevToMev(pimSp_modelB);
  data_pimSp-> SetLineWidth(3);
  data_pimSp-> SetMarkerStyle(8);
  data_pimSp-> SetMarkerColor(kRed);
  data_pimSp-> SetMarkerSize(1.2);
  data_pimSp-> GetXaxis()-> SetRangeUser(1.35, 1.55);
  data_pimSp-> GetYaxis()-> SetRangeUser(0., 30.);
  data_pimSp-> SetLineColor(kRed);
  pimSp_modelA-> GetYaxis()-> SetRangeUser(0, 30);
  // pimSp_modelA-> SetLineColor(kRed);
  // pimSp_modelB-> SetLineColor(kBlue);
  pimSp_modelA-> SetLineStyle(9);
  pimSp_modelA-> SetLineColor(kPink+2);
  pimSp_modelB-> SetLineColor(kOrange+2);
  pimSp_modelA-> SetLineWidth(3);
  pimSp_modelB-> SetLineWidth(3);
  pimSp_modelA-> GetYaxis()-> SetTitle("#frac{d^{2}#sigma}{d#Omega dm} #mub/sr MeV");
  pimSp_modelA-> GetXaxis()-> SetTitle("#pi #Sigma mass [GeV/c^{2}]");
  pimSp_modelA-> Draw("APL");
  pimSp_modelB-> Draw("PL");
  data_pimSp-> Draw("P");
  line.DrawLine(kpThre, 0., kpThre, 30);
  TLegend *leg=new TLegend(0.2, 0.6, 0.5, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(data_pimSp, "Data", "elp");
  leg-> AddEntry(pimSp_modelA, "Model.A", "lp");
  leg-> AddEntry(pimSp_modelB, "Model.B", "lp");
  leg-> Draw();
  c1-> Print("~/ag_Run78/pic/JPS_2022/DCC_pimSp_wData.eps");

  TGraphErrors *data_pipSm=(TGraphErrors*)f->Get("pipSm_CS0");
  TGraph *pipSm_modelA=(TGraph*)f->Get("pipSm_modelA_conv");
  TGraph *pipSm_modelB=(TGraph*)f->Get("pipSm_modelB_conv");
  data_pipSm-> GetYaxis()-> SetTitle("#frac{d^{2}#sigma}{d#Omega dm} #mub/sr MeV");
  data_pipSm-> GetXaxis()-> SetTitle("#pi #Sigma mass [GeV/c^{2}]");
  data_pipSm=GevToMev(data_pipSm);
  pipSm_modelA=GevToMev(pipSm_modelA);
  pipSm_modelB=GevToMev(pipSm_modelB);

  data_pipSm-> SetLineWidth(3);
  data_pipSm-> SetMarkerStyle(8);
  data_pipSm-> SetMarkerColor(kBlue);
  data_pipSm-> SetMarkerSize(1.2);
  data_pipSm-> GetXaxis()-> SetRangeUser(1.35, 1.55);
  data_pipSm-> GetYaxis()-> SetRangeUser(0., 30.);
  data_pipSm-> SetLineColor(kBlue);
  pipSm_modelA-> GetYaxis()-> SetRangeUser(0, 30);
  // pipSm_modelA-> SetLineColor(kBlue);
  // pipSm_modelB-> SetLineColor(kBlue);
  pipSm_modelA-> SetLineStyle(9);
  pipSm_modelA-> SetLineColor(kPink+2);
  pipSm_modelB-> SetLineColor(kOrange+2);
  pipSm_modelB-> SetLineStyle(1);
  pipSm_modelA-> SetLineWidth(3);
  pipSm_modelB-> SetLineWidth(3);
  pipSm_modelA-> GetYaxis()-> SetTitle("#frac{d^{2}#sigma}{d#Omega dm} #mub/sr MeV");
  pipSm_modelA-> GetXaxis()-> SetTitle("#pi #Sigma mass [GeV/c^{2}]");
  pipSm_modelA-> Draw("APL");
  pipSm_modelB-> Draw("PL");
  data_pipSm-> Draw("P");
  line.DrawLine(kpThre, 0., kpThre, 30);
  TLegend *leg=new TLegend(0.2, 0.6, 0.5, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(data_pipSm, "Data", "elp");
  leg-> AddEntry(pipSm_modelA, "Model.A", "lp");
  leg-> AddEntry(pipSm_modelB, "Model.B", "lp");
  leg-> Draw();
  c1-> Print("~/ag_Run78/pic/JPS_2022/DCC_pipSm_wData.eps");

  TGraphErrors *data_pimS0=(TGraphErrors*)f->Get("pimS0_CS0");
  TGraph *pimS0_modelA=(TGraph*)f->Get("pimS0_modelA_conv");
  TGraph *pimS0_modelB=(TGraph*)f->Get("pimS0_modelB_conv");
  data_pimS0-> GetYaxis()-> SetTitle("#frac{d^{2}#sigma}{d#Omega dm} #mub/sr MeV");
  data_pimS0-> GetXaxis()-> SetTitle("#pi #Sigma mass [GeV/c^{2}]");
  data_pimS0=GevToMev(data_pimS0);
  pimS0_modelA=GevToMev(pimS0_modelA);
  pimS0_modelB=GevToMev(pimS0_modelB);

  data_pimS0-> SetLineWidth(3);
  data_pimS0-> SetMarkerStyle(8);
  data_pimS0-> SetMarkerColor(3);
  data_pimS0-> SetMarkerSize(1.2);
  data_pimS0-> GetXaxis()-> SetRangeUser(1.35, 1.55);
  data_pimS0-> GetYaxis()-> SetRangeUser(0., 30.);
  data_pimS0-> SetLineColor(3);
  pimS0_modelA-> GetYaxis()-> SetRangeUser(0, 30);
  // pimS0_modelA-> SetLineColor(3);
  // pimS0_modelB-> SetLineColor(3);
  pimS0_modelA-> SetLineStyle(9);
  pimS0_modelA-> SetLineColor(kPink+2);
  pimS0_modelB-> SetLineColor(kOrange+2);
  pimS0_modelB-> SetLineStyle(1);
  pimS0_modelA-> SetLineWidth(3);
  pimS0_modelB-> SetLineWidth(3);
  pimS0_modelA-> GetYaxis()-> SetTitle("#frac{d^{2}#sigma}{d#Omega dm} #mub/sr MeV");
  pimS0_modelA-> GetXaxis()-> SetTitle("#pi #Sigma mass [GeV/c^{2}]");
  pimS0_modelA-> Draw("APL");
  pimS0_modelB-> Draw("PL");
  data_pimS0-> Draw("P");
  line.DrawLine(kpThre, 0., kpThre, 30);
  TLegend *leg=new TLegend(0.2, 0.6, 0.5, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(data_pimS0, "Data", "elp");
  leg-> AddEntry(pimS0_modelA, "Model.A", "lp");
  leg-> AddEntry(pimS0_modelB, "Model.B", "lp");
  leg-> Draw();
  c1-> Print("~/ag_Run78/pic/JPS_2022/DCC_pimS0_wData.eps");
}
