#include "../init.C"

const TString infileroot="~/fit_model_B.root";

void draw_fit_B_all(){
  init();
  TCanvas *c1 = new TCanvas("c1", "c1");
  
  TFile *f=new TFile(infileroot);
  TGraphErrors *gra_data_pimSp=(TGraphErrors*)f->Get("gra_pimSp_CS");
  TGraph *gra_pimSp_1=(TGraph*)f->Get("gra_pimSp_B_scale");
  TGraph *gra_pimSp_2=(TGraph*)f->Get("gra_pimSp_B");
  TGraph *gra_pimSp_3=(TGraph*)f->Get("gra_pimSp_B_fix_phase");
  gra_data_pimSp-> Draw("AP");
  gra_pimSp_1-> SetLineColor(46);
  gra_pimSp_2-> SetLineColor(38);
  gra_pimSp_3-> SetLineColor(30);
  gra_pimSp_1-> Draw("L");
  gra_pimSp_2-> Draw("L");
  gra_pimSp_3-> Draw("L");
  TLegend *leg =new TLegend(0.15, 0.65, 0.4, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(gra_pimSp_2, "3 param", "l");
  leg-> AddEntry(gra_pimSp_3, "", "l");
  leg-> AddEntry(gra_pimSp_1, "A_{I=0}, A_{I=1}", "l");
  leg-> AddEntry(gra_data_pimSp, "Data", "lep");
  leg-> Draw();
  c1-> Print("pic/Dron/fit_model_B_all_pimSp.eps");

  TGraphErrors *gra_data_pipSm=(TGraphErrors*)f->Get("gra_pipSm_CS");
  TGraph *gra_pipSm_1=(TGraph*)f->Get("gra_pipSm_B_scale");
  TGraph *gra_pipSm_2=(TGraph*)f->Get("gra_pipSm_B");
  TGraph *gra_pipSm_3=(TGraph*)f->Get("gra_pipSm_B_fix_phase");
  gra_data_pipSm-> Draw("AP");
  gra_pipSm_1-> SetLineColor(46);
  gra_pipSm_2-> SetLineColor(38);
  gra_pipSm_3-> SetLineColor(30);
  gra_pipSm_1-> Draw("L");
  gra_pipSm_2-> Draw("L");
  gra_pipSm_3-> Draw("L");
  leg =new TLegend(0.15, 0.65, 0.4, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(gra_pipSm_2, "3 param", "l");
  leg-> AddEntry(gra_pipSm_3, "", "l");
  leg-> AddEntry(gra_pipSm_1, "A_{I=0}, A_{I=1}", "l");
  leg-> AddEntry(gra_data_pipSm, "Data", "lep");
  leg-> Draw();
  c1-> Print("pic/Dron/fit_model_B_all_pipSm.eps");

  TGraphErrors *gra_data_pimS0=(TGraphErrors*)f->Get("gra_pimS0_CS");
  TGraph *gra_pimS0_1=(TGraph*)f->Get("gra_pimS0_B_scale");
  TGraph *gra_pimS0_2=(TGraph*)f->Get("gra_pimS0_B");
  TGraph *gra_pimS0_3=(TGraph*)f->Get("gra_pimS0_B_fix_phase");
  gra_data_pimS0-> Draw("AP");
  gra_pimS0_1-> SetLineColor(46);
  gra_pimS0_2-> SetLineColor(38);
  gra_pimS0_3-> SetLineColor(30);
  gra_pimS0_1-> Draw("L");
  gra_pimS0_2-> Draw("L");
  gra_pimS0_3-> Draw("L");
  leg =new TLegend(0.15, 0.65, 0.4, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(gra_pimS0_2, "3 param", "l");
  leg-> AddEntry(gra_pimS0_3, "", "l");
  leg-> AddEntry(gra_pimS0_1, "A_{I=0}, A_{I=1}", "l");
  leg-> AddEntry(gra_data_pimS0, "Data", "lep");
  leg-> Draw();
  c1-> Print("pic/Dron/fit_model_B_all_pimS0.eps");

  TGraphErrors *gra_data_I0=(TGraphErrors*)f->Get("gra_data_I0");
  TGraph *gra_I0_1=(TGraph*)f->Get("gra_I0_B_scale");
  TGraph *gra_I0_2=(TGraph*)f->Get("gra_I0_B");
  TGraph *gra_I0_3=(TGraph*)f->Get("gra_I0_B_fix_phase");
  gra_data_I0-> Draw("AP");
  gra_I0_1-> SetLineColor(46);
  gra_I0_2-> SetLineColor(38);
  gra_I0_3-> SetLineColor(30);
  gra_I0_1-> Draw("L");
  gra_I0_2-> Draw("L");
  gra_I0_3-> Draw("L");
  leg =new TLegend(0.15, 0.65, 0.4, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(gra_I0_2, "3 param", "l");
  leg-> AddEntry(gra_I0_3, "", "l");
  leg-> AddEntry(gra_I0_1, "A_{I=0}, A_{I=1}", "l");
  leg-> AddEntry(gra_data_I0, "Data", "lep");
  leg-> Draw();
  c1-> Print("pic/Dron/fit_model_B_all_I0.eps");

  TGraphErrors *gra_sub=(TGraphErrors*)f->Get("gra_sub");
  TGraph *gra_interfer_1=(TGraph*)f->Get("gra_interfer_B_scale");
  TGraph *gra_interfer_2=(TGraph*)f->Get("gra_interfer_B");
  TGraph *gra_interfer_3=(TGraph*)f->Get("gra_interfer_B_fix_phase");
  gra_sub-> Draw("AP");
  gra_interfer_1-> SetLineColor(46);
  gra_interfer_2-> SetLineColor(38);
  gra_interfer_3-> SetLineColor(30);
  gra_interfer_1-> Draw("L");
  gra_interfer_2-> Draw("L");
  gra_interfer_3-> Draw("L");
  leg =new TLegend(0.15, 0.65, 0.4, 0.95);
  leg-> SetFillStyle(0);
  leg-> SetBorderSize(0);
  leg-> AddEntry(gra_interfer_2, "3 param", "l");
  leg-> AddEntry(gra_interfer_3, "", "l");
  leg-> AddEntry(gra_interfer_1, "A_{I=0}, A_{I=1}", "l");
  leg-> AddEntry(gra_sub, "Data", "lep");
  leg-> Draw();
  c1-> Print("pic/Dron/fit_model_B_all_interfer.eps");
}
